# Minimal KalamDB Server Configuration - Node 3 (Docker Cluster)

[server]
host = "0.0.0.0"
port = 8080

[storage]
data_path = "/data"

[limits]

[logging]

[performance]

[cluster]
cluster_id = "docker-cluster"
node_id = 3
rpc_addr = "kalamdb-node3:9090"
api_addr = "http://kalamdb-node3:8080"

[[cluster.peers]]
node_id = 1
rpc_addr = "kalamdb-node1:9090"
api_addr = "http://kalamdb-node1:8080"

[[cluster.peers]]
node_id = 2
rpc_addr = "kalamdb-node2:9090"
api_addr = "http://kalamdb-node2:8080"
